apiVersion: v1
kind: Service
metadata:
  name: mnist-classifier-service
spec:
  selector:
    app: mnist-classifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer