apiVersion: apps/v1
kind: Deployment
metadata:
 name: mnist-classifier-deployment
spec:
 replicas: 3
 selector:
  matchLabels:
    app: mnist-classifier
 template:
 metadata:
  labels:
    app: mnist-classifier
 spec:
  containers:
  - name: mnist-classifier
  image: mnist-classifier:v1
  ports:
  - containerPort: 5000